var annotated_dup =
[
    [ "std", "namespacestd.html", [
      [ "hash< std::pair< int, int > >", "structstd_1_1hash_3_01std_1_1pair_3_01int_00_01int_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1pair_3_01int_00_01int_01_4_01_4" ]
    ] ],
    [ "Arc", "structArc.html", "structArc" ],
    [ "arc_map_hash", "structarc__map__hash.html", "structarc__map__hash" ],
    [ "ArcDuals", "classArcDuals.html", "classArcDuals" ],
    [ "BNBNode", "classBNBNode.html", "classBNBNode" ],
    [ "BNBNodeCompare", "structBNBNodeCompare.html", "structBNBNodeCompare" ],
    [ "BranchAndBound", "classBranchAndBound.html", "classBranchAndBound" ],
    [ "Branching", "classBranching.html", "classBranching" ],
    [ "BranchingDuals", "classBranchingDuals.html", "classBranchingDuals" ],
    [ "BranchingQueueItem", "structBranchingQueueItem.html", "structBranchingQueueItem" ],
    [ "Bucket", "structBucket.html", "structBucket" ],
    [ "BucketArc", "structBucketArc.html", "structBucketArc" ],
    [ "BucketGraph", "classBucketGraph.html", "classBucketGraph" ],
    [ "BucketIntervalTree", "classBucketIntervalTree.html", "classBucketIntervalTree" ],
    [ "BucketOptions", "structBucketOptions.html", "structBucketOptions" ],
    [ "BucketRange", "structBucketRange.html", "structBucketRange" ],
    [ "CholmodSolver", "classCholmodSolver.html", "classCholmodSolver" ],
    [ "CliqueManager", "classCliqueManager.html", "classCliqueManager" ],
    [ "CompareCuts", "structCompareCuts.html", "structCompareCuts" ],
    [ "Cut", "structCut.html", "structCut" ],
    [ "CutStorage", "classCutStorage.html", "classCutStorage" ],
    [ "HGS", "classHGS.html", "classHGS" ],
    [ "InstanceData", "structInstanceData.html", "structInstanceData" ],
    [ "Interval", "structInterval.html", "structInterval" ],
    [ "IntervalNode", "structIntervalNode.html", "structIntervalNode" ],
    [ "IntervalTree", "classIntervalTree.html", "classIntervalTree" ],
    [ "IPSolver", "classIPSolver.html", "classIPSolver" ],
    [ "JumpArc", "structJumpArc.html", "structJumpArc" ],
    [ "Knapsack", "classKnapsack.html", "classKnapsack" ],
    [ "Label", "structLabel.html", "structLabel" ],
    [ "LabelComparator", "classLabelComparator.html", "classLabelComparator" ],
    [ "LabelPool", "classLabelPool.html", "classLabelPool" ],
    [ "LimitedMemoryRank1Cuts", "classLimitedMemoryRank1Cuts.html", "classLimitedMemoryRank1Cuts" ],
    [ "MemoryPool", "classMemoryPool.html", "classMemoryPool" ],
    [ "ModelData", "structModelData.html", "structModelData" ],
    [ "NodeDuals", "classNodeDuals.html", "classNodeDuals" ],
    [ "NumericUtils", "structNumericUtils.html", null ],
    [ "OptimizationData", "structOptimizationData.html", "structOptimizationData" ],
    [ "Path", "structPath.html", "structPath" ],
    [ "PathHash", "structPathHash.html", "structPathHash" ],
    [ "PoolAllocator", "classPoolAllocator.html", "classPoolAllocator" ],
    [ "Preprocessor", "classPreprocessor.html", "classPreprocessor" ],
    [ "PresolveResult", "structPresolveResult.html", "structPresolveResult" ],
    [ "Problem", "classProblem.html", "classProblem" ],
    [ "PSTEPDuals", "structPSTEPDuals.html", "structPSTEPDuals" ],
    [ "RawArc", "structRawArc.html", "structRawArc" ],
    [ "RawArcHash", "structRawArcHash.html", "structRawArcHash" ],
    [ "RCCManager", "classRCCManager.html", "classRCCManager" ],
    [ "RCCut", "structRCCut.html", "structRCCut" ],
    [ "Residuals", "structResiduals.html", "structResiduals" ],
    [ "RowActivity", "structRowActivity.html", "structRowActivity" ],
    [ "RowInfo", "structRowInfo.html", "structRowInfo" ],
    [ "SCC", "classSCC.html", "classSCC" ],
    [ "SchrodingerPool", "classSchrodingerPool.html", "classSchrodingerPool" ],
    [ "SparseElement", "structSparseElement.html", "structSparseElement" ],
    [ "SparseMatrix", "structSparseMatrix.html", "structSparseMatrix" ],
    [ "SparseSolver", "classSparseSolver.html", "classSparseSolver" ],
    [ "SplayTree", "classSplayTree.html", "classSplayTree" ],
    [ "Stabilization", "classStabilization.html", "classStabilization" ],
    [ "TreeNode", "classTreeNode.html", "classTreeNode" ],
    [ "VRPCandidate", "classVRPCandidate.html", "classVRPCandidate" ],
    [ "VRPNode", "structVRPNode.html", "structVRPNode" ],
    [ "VRPTW_SRC", "structVRPTW__SRC.html", "structVRPTW__SRC" ]
];