var annotated_dup =
[
    [ "Eigen", "namespaceEigen.html", [
      [ "CustomSimplicialLDLT", "classEigen_1_1CustomSimplicialLDLT.html", "classEigen_1_1CustomSimplicialLDLT" ]
    ] ],
    [ "serializer", "namespaceserializer.html", [
      [ "SerializationBuffer", "classserializer_1_1SerializationBuffer.html", "classserializer_1_1SerializationBuffer" ],
      [ "SerializationError", "classserializer_1_1SerializationError.html", null ],
      [ "Serializer", "classserializer_1_1Serializer.html", null ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Bitset< N_BITS > >", "structstd_1_1hash_3_01Bitset_3_01N__BITS_01_4_01_4.html", "structstd_1_1hash_3_01Bitset_3_01N__BITS_01_4_01_4" ],
      [ "hash< CandidateSet >", "structstd_1_1hash_3_01CandidateSet_01_4.html", "structstd_1_1hash_3_01CandidateSet_01_4" ],
      [ "hash< std::pair< int, int > >", "structstd_1_1hash_3_01std_1_1pair_3_01int_00_01int_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1pair_3_01int_00_01int_01_4_01_4" ],
      [ "hash< std::vector< int > >", "structstd_1_1hash_3_01std_1_1vector_3_01int_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1vector_3_01int_01_4_01_4" ]
    ] ],
    [ "ActiveCutInfo", "structActiveCutInfo.html", "structActiveCutInfo" ],
    [ "AdaptiveNodeScorer", "classAdaptiveNodeScorer.html", "classAdaptiveNodeScorer" ],
    [ "Arc", "structArc.html", "structArc" ],
    [ "arc_hash", "structarc__hash.html", "structarc__hash" ],
    [ "arc_map_hash", "structarc__map__hash.html", "structarc__map__hash" ],
    [ "ArcDuals", "classArcDuals.html", "classArcDuals" ],
    [ "ArcList", "classArcList.html", "classArcList" ],
    [ "ATSPInstance", "classATSPInstance.html", "classATSPInstance" ],
    [ "baldesCtr", "classbaldesCtr.html", "classbaldesCtr" ],
    [ "baldesVar", "classbaldesVar.html", "classbaldesVar" ],
    [ "Bitset", "classBitset.html", "classBitset" ],
    [ "BNBNode", "classBNBNode.html", "classBNBNode" ],
    [ "BNBNodeCompare", "structBNBNodeCompare.html", "structBNBNodeCompare" ],
    [ "BranchAndBound", "classBranchAndBound.html", "classBranchAndBound" ],
    [ "Branching", "classBranching.html", "classBranching" ],
    [ "BranchingDuals", "classBranchingDuals.html", "classBranchingDuals" ],
    [ "BranchingQueueItem", "structBranchingQueueItem.html", "structBranchingQueueItem" ],
    [ "Bucket", "structBucket.html", "structBucket" ],
    [ "BucketArc", "structBucketArc.html", "structBucketArc" ],
    [ "BucketGraph", "classBucketGraph.html", "classBucketGraph" ],
    [ "BucketOptions", "structBucketOptions.html", "structBucketOptions" ],
    [ "CachedCut", "structCachedCut.html", "structCachedCut" ],
    [ "CandidateSet", "structCandidateSet.html", "structCandidateSet" ],
    [ "CandidateSetCompare", "structCandidateSetCompare.html", "structCandidateSetCompare" ],
    [ "CandidateSetHasher", "structCandidateSetHasher.html", "structCandidateSetHasher" ],
    [ "CliqueManager", "classCliqueManager.html", "classCliqueManager" ],
    [ "CostFunction", "classCostFunction.html", "classCostFunction" ],
    [ "CS", "structCS.html", "structCS" ],
    [ "CustomMatIterator", "classCustomMatIterator.html", "classCustomMatIterator" ],
    [ "Cut", "structCut.html", "structCut" ],
    [ "CutStorage", "classCutStorage.html", "classCutStorage" ],
    [ "CycleData", "structCycleData.html", "structCycleData" ],
    [ "GenericParameters", "classGenericParameters.html", "classGenericParameters" ],
    [ "GRBModelWrapper", "structGRBModelWrapper.html", "structGRBModelWrapper" ],
    [ "GurobiEnvSingleton", "classGurobiEnvSingleton.html", "classGurobiEnvSingleton" ],
    [ "GurobiSolver", "classGurobiSolver.html", "classGurobiSolver" ],
    [ "HGS", "classHGS.html", "classHGS" ],
    [ "HighRankCuts", "classHighRankCuts.html", "classHighRankCuts" ],
    [ "HighsSolver", "classHighsSolver.html", "classHighsSolver" ],
    [ "InstanceData", "structInstanceData.html", "structInstanceData" ],
    [ "Interval", "structInterval.html", "structInterval" ],
    [ "IPMSolver", "classIPMSolver.html", "classIPMSolver" ],
    [ "IPSolver", "classIPSolver.html", "classIPSolver" ],
    [ "IteratedLocalSearch", "classIteratedLocalSearch.html", "classIteratedLocalSearch" ],
    [ "JumpArc", "structJumpArc.html", "structJumpArc" ],
    [ "Knapsack", "classKnapsack.html", "classKnapsack" ],
    [ "Label", "structLabel.html", "structLabel" ],
    [ "LabelComparator", "classLabelComparator.html", "classLabelComparator" ],
    [ "LabelPool", "classLabelPool.html", "classLabelPool" ],
    [ "LimitedMemoryRank1Cuts", "classLimitedMemoryRank1Cuts.html", "classLimitedMemoryRank1Cuts" ],
    [ "LinearExpression", "classLinearExpression.html", "classLinearExpression" ],
    [ "LocalSearch", "classLocalSearch.html", "classLocalSearch" ],
    [ "Logger", "classLogger.html", null ],
    [ "MIPColumn", "classMIPColumn.html", "classMIPColumn" ],
    [ "MIPProblem", "classMIPProblem.html", "classMIPProblem" ],
    [ "ModelData", "structModelData.html", "structModelData" ],
    [ "MST", "classMST.html", "classMST" ],
    [ "MultiPointManager", "classMultiPointManager.html", "classMultiPointManager" ],
    [ "NodeDuals", "classNodeDuals.html", "classNodeDuals" ],
    [ "NodeScore", "structNodeScore.html", "structNodeScore" ],
    [ "NumericUtils", "structNumericUtils.html", null ],
    [ "OptimizationData", "structOptimizationData.html", "structOptimizationData" ],
    [ "ParametersBuilder", "classParametersBuilder.html", "classParametersBuilder" ],
    [ "ParamType", "structParamType.html", "structParamType" ],
    [ "Path", "structPath.html", "structPath" ],
    [ "PathHash", "structPathHash.html", "structPathHash" ],
    [ "Permutation", "classPermutation.html", "classPermutation" ],
    [ "POPMUSIC", "classPOPMUSIC.html", "classPOPMUSIC" ],
    [ "Preprocessor", "classPreprocessor.html", "classPreprocessor" ],
    [ "PresolveResult", "structPresolveResult.html", "structPresolveResult" ],
    [ "Problem", "classProblem.html", "classProblem" ],
    [ "PSTEPDuals", "structPSTEPDuals.html", "structPSTEPDuals" ],
    [ "RawArc", "structRawArc.html", "structRawArc" ],
    [ "RawArcHash", "structRawArcHash.html", "structRawArcHash" ],
    [ "RawArcList", "classRawArcList.html", "classRawArcList" ],
    [ "RCCManager", "classRCCManager.html", "classRCCManager" ],
    [ "RCCut", "structRCCut.html", "structRCCut" ],
    [ "ReducedCostResult", "structReducedCostResult.html", "structReducedCostResult" ],
    [ "Residuals", "structResiduals.html", "structResiduals" ],
    [ "RouteCache", "classRouteCache.html", "classRouteCache" ],
    [ "RowActivity", "structRowActivity.html", "structRowActivity" ],
    [ "RowInfo", "structRowInfo.html", "structRowInfo" ],
    [ "ScalingFactors", "structScalingFactors.html", "structScalingFactors" ],
    [ "SCC", "classSCC.html", "classSCC" ],
    [ "SchrodingerPool", "classSchrodingerPool.html", "classSchrodingerPool" ],
    [ "Snapshot", "structSnapshot.html", "structSnapshot" ],
    [ "Solution", "structSolution.html", "structSolution" ],
    [ "SolverInterface", "classSolverInterface.html", "classSolverInterface" ],
    [ "SparseMatrix", "structSparseMatrix.html", "structSparseMatrix" ],
    [ "SparseSolver", "classSparseSolver.html", "classSparseSolver" ],
    [ "SparseSolveTriangular", "structSparseSolveTriangular.html", "structSparseSolveTriangular" ],
    [ "SplayTree", "classSplayTree.html", "classSplayTree" ],
    [ "SRCPermutation", "structSRCPermutation.html", "structSRCPermutation" ],
    [ "Stabilization", "classStabilization.html", "classStabilization" ],
    [ "Supernodal", "classSupernodal.html", "classSupernodal" ],
    [ "TaskQueue", "classTaskQueue.html", "classTaskQueue" ],
    [ "ThreadLocalPool", "classThreadLocalPool.html", "classThreadLocalPool" ],
    [ "TreeNode", "classTreeNode.html", "classTreeNode" ],
    [ "TrustRegion", "classTrustRegion.html", "classTrustRegion" ],
    [ "type_to_index", "structtype__to__index.html", null ],
    [ "type_to_index< double >", "structtype__to__index_3_01double_01_4.html", null ],
    [ "type_to_index< int >", "structtype__to__index_3_01int_01_4.html", null ],
    [ "UnionFind", "classUnionFind.html", "classUnionFind" ],
    [ "VectorHash", "structVectorHash.html", "structVectorHash" ],
    [ "VectorIntHash", "structVectorIntHash.html", "structVectorIntHash" ],
    [ "VectorIntHashCompare", "structVectorIntHashCompare.html", "structVectorIntHashCompare" ],
    [ "VRPCandidate", "classVRPCandidate.html", "classVRPCandidate" ],
    [ "VRPNode", "structVRPNode.html", "structVRPNode" ],
    [ "VRProblem", "classVRProblem.html", "classVRProblem" ],
    [ "Xoroshiro128Plus", "classXoroshiro128Plus.html", "classXoroshiro128Plus" ]
];