var hierarchy =
[
    [ "Arc", "structArc.html", null ],
    [ "arc_map_hash", "structarc__map__hash.html", null ],
    [ "ArcDuals", "classArcDuals.html", null ],
    [ "BNBNodeCompare", "structBNBNodeCompare.html", null ],
    [ "BranchAndBound", "classBranchAndBound.html", null ],
    [ "Branching", "classBranching.html", null ],
    [ "BranchingDuals", "classBranchingDuals.html", null ],
    [ "BranchingQueueItem", "structBranchingQueueItem.html", null ],
    [ "Bucket", "structBucket.html", null ],
    [ "BucketArc", "structBucketArc.html", null ],
    [ "BucketGraph", "classBucketGraph.html", null ],
    [ "BucketIntervalTree< D >", "classBucketIntervalTree.html", null ],
    [ "BucketOptions", "structBucketOptions.html", null ],
    [ "BucketRange< D >", "structBucketRange.html", null ],
    [ "CholmodSolver", "classCholmodSolver.html", null ],
    [ "CliqueManager", "classCliqueManager.html", null ],
    [ "CompareCuts", "structCompareCuts.html", null ],
    [ "Cut", "structCut.html", null ],
    [ "CutStorage", "classCutStorage.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "BNBNode", "classBNBNode.html", null ]
    ] ],
    [ "std::hash< std::pair< int, int > >", "structstd_1_1hash_3_01std_1_1pair_3_01int_00_01int_01_4_01_4.html", null ],
    [ "HGS", "classHGS.html", null ],
    [ "InstanceData", "structInstanceData.html", null ],
    [ "Interval", "structInterval.html", null ],
    [ "IntervalNode< D >", "structIntervalNode.html", null ],
    [ "IntervalTree< D >", "classIntervalTree.html", null ],
    [ "IPSolver", "classIPSolver.html", null ],
    [ "JumpArc", "structJumpArc.html", null ],
    [ "Knapsack", "classKnapsack.html", null ],
    [ "Label", "structLabel.html", null ],
    [ "LabelComparator", "classLabelComparator.html", null ],
    [ "LabelPool", "classLabelPool.html", null ],
    [ "LimitedMemoryRank1Cuts", "classLimitedMemoryRank1Cuts.html", null ],
    [ "std::pmr::memory_resource", null, [
      [ "MemoryPool", "classMemoryPool.html", null ]
    ] ],
    [ "ModelData", "structModelData.html", null ],
    [ "NodeDuals", "classNodeDuals.html", null ],
    [ "NumericUtils", "structNumericUtils.html", null ],
    [ "OptimizationData", "structOptimizationData.html", null ],
    [ "Path", "structPath.html", null ],
    [ "PathHash", "structPathHash.html", null ],
    [ "PoolAllocator< T >", "classPoolAllocator.html", null ],
    [ "Preprocessor", "classPreprocessor.html", null ],
    [ "PresolveResult", "structPresolveResult.html", null ],
    [ "Problem", "classProblem.html", null ],
    [ "PSTEPDuals", "structPSTEPDuals.html", null ],
    [ "RawArc", "structRawArc.html", null ],
    [ "RawArcHash", "structRawArcHash.html", null ],
    [ "RCCManager", "classRCCManager.html", null ],
    [ "RCCut", "structRCCut.html", null ],
    [ "Residuals", "structResiduals.html", null ],
    [ "RowActivity", "structRowActivity.html", null ],
    [ "RowInfo", "structRowInfo.html", null ],
    [ "SparseMatrix::RowIterator", "structSparseMatrix_1_1RowIterator.html", null ],
    [ "SCC", "classSCC.html", null ],
    [ "SchrodingerPool", "classSchrodingerPool.html", null ],
    [ "SparseElement", "structSparseElement.html", null ],
    [ "SparseMatrix", "structSparseMatrix.html", null ],
    [ "SparseSolver", "classSparseSolver.html", null ],
    [ "SplayTree", "classSplayTree.html", null ],
    [ "Stabilization", "classStabilization.html", null ],
    [ "TreeNode", "classTreeNode.html", null ],
    [ "VRPCandidate", "classVRPCandidate.html", null ],
    [ "VRPNode", "structVRPNode.html", null ],
    [ "VRPTW_SRC", "structVRPTW__SRC.html", null ]
];