var hierarchy =
[
    [ "CutStorage::ActiveCutInfo", "structCutStorage_1_1ActiveCutInfo.html", null ],
    [ "HighDimCutsGenerator::aligned_allocator< T, Alignment >", "structHighDimCutsGenerator_1_1aligned__allocator.html", null ],
    [ "Arc", "structArc.html", null ],
    [ "arc_map_hash", "structarc__map__hash.html", null ],
    [ "ArcDuals", "classArcDuals.html", null ],
    [ "Path::ArcKey", "structPath_1_1ArcKey.html", null ],
    [ "Path::ArcKeyHash", "structPath_1_1ArcKeyHash.html", null ],
    [ "ArcList", "classArcList.html", null ],
    [ "ATSPInstance", "classATSPInstance.html", null ],
    [ "baldesCtr", "classbaldesCtr.html", null ],
    [ "Bitset< N_BITS >", "classBitset.html", null ],
    [ "BNBNodeCompare", "structBNBNodeCompare.html", null ],
    [ "BranchAndBound", "classBranchAndBound.html", null ],
    [ "Branching", "classBranching.html", null ],
    [ "BranchingDuals", "classBranchingDuals.html", null ],
    [ "BranchingQueueItem", "structBranchingQueueItem.html", null ],
    [ "Bucket", "structBucket.html", null ],
    [ "BucketArc", "structBucketArc.html", null ],
    [ "BucketGraph", "classBucketGraph.html", null ],
    [ "BucketOptions", "structBucketOptions.html", null ],
    [ "CachedCut", "structCachedCut.html", null ],
    [ "CliqueManager", "classCliqueManager.html", null ],
    [ "HighDimCutsGenerator::Cluster", "structHighDimCutsGenerator_1_1Cluster.html", null ],
    [ "MultiPointManager::Config", "structMultiPointManager_1_1Config.html", null ],
    [ "CostFunction", "classCostFunction.html", null ],
    [ "SparseMatrix::CRSData", "structSparseMatrix_1_1CRSData.html", null ],
    [ "CS", "structCS.html", null ],
    [ "CustomMatIterator< MatrixType >", "classCustomMatIterator.html", null ],
    [ "Eigen::CustomSimplicialLDLT< MatrixType_, UpLo_, Ordering_ >", "classEigen_1_1CustomSimplicialLDLT.html", null ],
    [ "Cut", "structCut.html", null ],
    [ "CutStorage", "classCutStorage.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "BNBNode", "classBNBNode.html", null ],
      [ "baldesVar", "classbaldesVar.html", null ]
    ] ],
    [ "GenericParameters", "classGenericParameters.html", null ],
    [ "GRBModelWrapper", "structGRBModelWrapper.html", null ],
    [ "GurobiEnvSingleton", "classGurobiEnvSingleton.html", null ],
    [ "std::hash< Bitset< N_BITS > >", "structstd_1_1hash_3_01Bitset_3_01N__BITS_01_4_01_4.html", null ],
    [ "std::hash< std::pair< int, int > >", "structstd_1_1hash_3_01std_1_1pair_3_01int_00_01int_01_4_01_4.html", null ],
    [ "HGS", "classHGS.html", null ],
    [ "HighDimCutsGenerator", "classHighDimCutsGenerator.html", null ],
    [ "HighRankCuts< RANK >", "classHighRankCuts.html", null ],
    [ "InstanceData", "structInstanceData.html", null ],
    [ "Interval", "structInterval.html", null ],
    [ "IPSolver", "classIPSolver.html", null ],
    [ "IteratedLocalSearch", "classIteratedLocalSearch.html", null ],
    [ "JumpArc", "structJumpArc.html", null ],
    [ "Knapsack", "classKnapsack.html", null ],
    [ "Label", "structLabel.html", null ],
    [ "LabelComparator", "classLabelComparator.html", null ],
    [ "LabelPool", "classLabelPool.html", null ],
    [ "LimitedMemoryRank1Cuts", "classLimitedMemoryRank1Cuts.html", null ],
    [ "LinearExpression", "classLinearExpression.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "MultiPointManager::Metrics", "structMultiPointManager_1_1Metrics.html", null ],
    [ "MIPColumn", "classMIPColumn.html", null ],
    [ "MIPProblem", "classMIPProblem.html", null ],
    [ "ModelData", "structModelData.html", null ],
    [ "HighDimCutsGenerator::MoveResult", "structHighDimCutsGenerator_1_1MoveResult.html", null ],
    [ "MST", "classMST.html", null ],
    [ "MultiPointManager", "classMultiPointManager.html", null ],
    [ "MUSSP", "classMUSSP.html", null ],
    [ "MUSSP::Node", "structMUSSP_1_1Node.html", null ],
    [ "NodeDuals", "classNodeDuals.html", null ],
    [ "NumericUtils", "structNumericUtils.html", null ],
    [ "OptimizationData", "structOptimizationData.html", null ],
    [ "ParametersBuilder", "classParametersBuilder.html", null ],
    [ "ParamType< T >", "structParamType.html", null ],
    [ "Path", "structPath.html", null ],
    [ "PathHash", "structPathHash.html", null ],
    [ "PDLP", "classPDLP.html", null ],
    [ "Permutation", "structPermutation.html", null ],
    [ "PlanValidationResult", "structPlanValidationResult.html", null ],
    [ "POPMUSIC", "classPOPMUSIC.html", null ],
    [ "Preprocessor", "classPreprocessor.html", null ],
    [ "PresolveResult", "structPresolveResult.html", null ],
    [ "Problem", "classProblem.html", null ],
    [ "PSTEPDuals", "structPSTEPDuals.html", null ],
    [ "R1c", "structR1c.html", null ],
    [ "HighDimCutsGenerator::R1CMemory", "structHighDimCutsGenerator_1_1R1CMemory.html", null ],
    [ "Rank1MultiLabel", "structRank1MultiLabel.html", null ],
    [ "RawArc", "structRawArc.html", null ],
    [ "RawArcHash", "structRawArcHash.html", null ],
    [ "RawArcList", "classRawArcList.html", null ],
    [ "RCCManager", "classRCCManager.html", null ],
    [ "RCCut", "structRCCut.html", null ],
    [ "HighDimCutsGenerator::aligned_allocator< T, Alignment >::rebind< U >", "structHighDimCutsGenerator_1_1aligned__allocator_1_1rebind.html", null ],
    [ "ReducedCostResult", "structReducedCostResult.html", null ],
    [ "Residuals", "structResiduals.html", null ],
    [ "RouteCache", "classRouteCache.html", null ],
    [ "RowActivity", "structRowActivity.html", null ],
    [ "RowInfo", "structRowInfo.html", null ],
    [ "SparseMatrix::RowIterator", "classSparseMatrix_1_1RowIterator.html", null ],
    [ "ScalingFactors", "structScalingFactors.html", null ],
    [ "SCC", "classSCC.html", null ],
    [ "SchrodingerPool", "classSchrodingerPool.html", null ],
    [ "Solution", "structSolution.html", null ],
    [ "SolverInterface", "classSolverInterface.html", [
      [ "GurobiSolver", "classGurobiSolver.html", null ],
      [ "HighsSolver", "classHighsSolver.html", null ],
      [ "IPMSolver", "classIPMSolver.html", null ]
    ] ],
    [ "SparseMatrix", "structSparseMatrix.html", null ],
    [ "SparseSolver", "classSparseSolver.html", null ],
    [ "Eigen::CustomSimplicialLDLT< MatrixType_, UpLo_, Ordering_ >::SparseSolveTriangular< Lhs, Rhs, Mode, IsLower, IsRowMajor >", "structEigen_1_1CustomSimplicialLDLT_1_1SparseSolveTriangular.html", null ],
    [ "SparseSolveTriangular< Lhs, Rhs, Mode, IsLower, IsRowMajor >", "structSparseSolveTriangular.html", null ],
    [ "SplayTree", "classSplayTree.html", null ],
    [ "SRCPermutation", "structSRCPermutation.html", null ],
    [ "MultiPointManager::StabilityPoint", "structMultiPointManager_1_1StabilityPoint.html", null ],
    [ "Stabilization", "classStabilization.html", null ],
    [ "HighDimCutsGenerator::State", "structHighDimCutsGenerator_1_1State.html", null ],
    [ "Supernodal< Scalar, StorageIndex >", "classSupernodal.html", null ],
    [ "TaskQueue< TaskType, MotherClass >", "classTaskQueue.html", null ],
    [ "ThreadLocalPool< T >", "classThreadLocalPool.html", null ],
    [ "TreeNode", "classTreeNode.html", null ],
    [ "TrustRegion", "classTrustRegion.html", null ],
    [ "Ts...", null, [
      [ "HighDimCutsGenerator::overloaded< Ts >", "structHighDimCutsGenerator_1_1overloaded.html", null ]
    ] ],
    [ "type_to_index< T >", "structtype__to__index.html", null ],
    [ "type_to_index< double >", "structtype__to__index_3_01double_01_4.html", null ],
    [ "type_to_index< int >", "structtype__to__index_3_01int_01_4.html", null ],
    [ "UnionFind", "classUnionFind.html", null ],
    [ "VectorHash", "structVectorHash.html", null ],
    [ "VectorIntHash", "structVectorIntHash.html", null ],
    [ "VectorIntHashCompare", "structVectorIntHashCompare.html", null ],
    [ "HighDimCutsGenerator::ViolationResult", "structHighDimCutsGenerator_1_1ViolationResult.html", null ],
    [ "VRPCandidate", "classVRPCandidate.html", null ],
    [ "VRPNode", "structVRPNode.html", null ],
    [ "VRProblem", "classVRProblem.html", null ],
    [ "Xoroshiro128Plus", "classXoroshiro128Plus.html", null ]
];