name: Documentation

on:
  push:
    branches: [ main ]


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    name: "Doxygen"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: './Doxyfile'

      - name: Move to docs/ subdirectory
        run: |
          rm -rf docs/html html
          mkdir -p docs/html
          cp -r html docs/html/ 2>/dev/null || true

      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          keep_files: true
          enable_jekyll: false
          allow_empty_commit: false
          publish_branch: gh-pages
